---
title: "Project 1 Checkpoint 3"
author: "Mira Griffin, Eloise Melendez, Chloe Schurter"
format: html
---

```{r}
#| label: packages-setup
#| message: false
#| warning: false
#| 

library(httr)
library(tidyjson)
library(jsonlite)
library(tidyverse)
library(glue)

cases_month <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_month.csv')
cases_year <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_year.csv')
```

```{r}
#| eval: false

base_url <- "https://api.api-ninjas.com/v1/country"

my_key <- "Y1uFEyHRSSkY4CU7PAkQfmHI8VsM3mvv75xLtbM4"

country = "USA"

USA_url <- glue("{base_url}?name={country};X-Api-Key={my_key}")

USA <- fromJSON(USA_url)

USA_urban <- USA |>
  select(urban_population) |>
  mutate(iso3 = country)

```

Function for getting urban population for a country:
```{r}
get_urban_pop <- function(country) {
  base_url <- "https://api.api-ninjas.com/v1/country"
  my_key <- "Y1uFEyHRSSkY4CU7PAkQfmHI8VsM3mvv75xLtbM4"
  my_url <- glue("{base_url}?name={country};X-Api-Key={my_key}")
  country_data <- fromJSON(my_url)
  
  country_urban_pop <- country_data |>
  select(urban_population) |>
  mutate(iso3 = country)
  
  return(country_urban_pop)
}

get_urban_pop("GBR")

```


Applying Function to all countries in data frame:
```{r}
unique_countries <- cases_year |>
  select(iso3) |>
  distinct() |>
  pull()

urban_pops <- map(unique_countries, get_urban_pop)
write.csv(urban_pops, "Urban Population Percentage.csv")
```

Combining data frames:
```{r}
urban_df <- bind_rows(urban_pops)


cases_year_urban_pop <- left_join(cases_year, urban_df, by = "iso3")
```


Summarizing mean incidence rate by urban population data

```{r}

library(dplyr)

cases_year_urban_pop_df <- as.data.frame(cases_year_urban_pop)

summarize_by_country <- cases_year_urban_pop_df |>
  group_by(iso3) |>
  summarize(
    mean_urbn_pop = mean(urban_population),
    mean = mean(measles_incidence_rate_per_1000000_total_population, na.rm = TRUE),
    median = median(measles_incidence_rate_per_1000000_total_population, na.rm = TRUE),
    sd = sd(measles_incidence_rate_per_1000000_total_population, na.rm = TRUE),
    min = min(measles_incidence_rate_per_1000000_total_population, na.rm = TRUE),
    max = max(measles_incidence_rate_per_1000000_total_population, na.rm = TRUE)
    ) |>
  arrange(desc(mean_urbn_pop))

summarize_by_country
```


Summarizing mean incidence rate by income group data

```{r}
library(dplyr)

names(ChildImmunizationIncomeGroup)

ChildImmunizationIncomeGroup <- ChildImmunizationIncomeGroup |>
  rename(iso3 = `Country Code`)

df <- ChildImmunizationIncomeGroup |>
  group_by(IncomeGroup) |>
  select(iso3, IncomeGroup)
df

df2 <- cases_year_urban_pop_df |>
  group_by(iso3) |>
  select(iso3, measles_incidence_rate_per_1000000_total_population, year)
df2

final_df <- df2 |>
  left_join(df, by = "iso3")

final_df

avg_measles_by_income <- final_df |>
  group_by(IncomeGroup) |>
  summarize(
    mean = mean(measles_incidence_rate_per_1000000_total_population),
    median = median(measles_incidence_rate_per_1000000_total_population),
    sd = sd(measles_incidence_rate_per_1000000_total_population),
    min = min(measles_incidence_rate_per_1000000_total_population),
    max = max(measles_incidence_rate_per_1000000_total_population)
    )

avg_measles_by_income

```

Meta Data Set

```{r}

meta_data_set <- cases_year_urban_pop |>
  left_join(ChildImmunizationIncomeGroup, by = "iso3")

```



